#!/bin/sh

./gradlew spotlessApply
if [ $? -ne 0 ]; then
  echo "spotlessApply failed. Commit aborted."
  exit 1
fi

./gradlew checkstyleMain
if [ $? -ne 0 ]; then
  echo "checkstyleMain failed. Commit aborted."
  exit 1
fi

git add .