main: com.storytimeproductions.stweaks.Stweaks
name: Stweaks
version: "1.0.0"
api-version: "1.21.4"
author: StoryTimeProductions
description: A collection of in-house tweaks for the StoryTime SMP. Currently includes the Stracker module for daily playtime tracking.

commands:
  ststatus:
    description: Shows how much time you've actively played today
    usage: /ststatus
    aliases: status
  stboost:
    description: Boosts multiplier for community participation (WIP)
    usage: "/stboost"
    aliases: boost
  stlobby:
    description: Teleport to the lobby
    usage: /stlobby
    aliases: lobby
  spawn:
    description: Teleports you to the spawn location in the world
    usage: /stspawn
    aliases: spawn
  biometracker:
    description: Opens the biome tracker GUI
    usage: /biometracker
  stquests:
    description: Opens the quests GUI
    usage: /stquests
    aliases: quests
  stpets:
    description: Opens the pets GUI
    usage: /stpets
    aliases: pets
  stcosmetics:
    description: Opens the cosmetics GUI
    usage: /stcosmetics
    aliases: cosmetics
  stcasino:
    description: Opens the casino GUI
    usage: /stcasino
    aliases: casino
  stdisguise:
    description: Manage entity disguises in the lobby
    usage: /disguise [apply|remove|reload]
  hunt:
    description: Opens the Hunt game lobby
    usage: /hunt [join|leave|status]
    aliases: [ huntlobby, huntgame ]

permissions:
  stweaks.stpets:
    description: Allows access to /stpets
    default: true
  stweaks.status:
    description: Allows access to /ststatus
    default: true
  stweaks.boost:
    description: Allows use of /stboost
    default: op
  stweaks.lobby:
    description: Allows access to /stlobby
    default: true
  stweaks.spawn:
    description: Allows access to /stspawn
    default: true
  stweaks.biometracker:
    description: Allows access to /biometracker
    default: true
  stweaks.quests:
    description: Allows access to /stquests
    default: true
  stweaks.cosmetics:
    description: Allows access to /stcosmetics
    default: true
  stweaks.disguise:
    description: Allows access to /stdisguise command
    default: op
  stweaks.*:
    description: Grants all Stweaks permissions
    default: false
    children:
      stweaks.status: true
      stweaks.boost: true
      stweaks.lobby: true
      stweaks.spawn: true
      stweaks.biometracker: true
      stweaks.quests: true
      stweaks.pets: true
      stweaks.cosmetics: true
      stweaks.disguise: true

depend:
- LibsDisguises
- DecentHolograms

softdepend:
- EntitySize
