main: com.storytimeproductions.stweaks.Stweaks
name: Stweaks
version: "1.0.0"
api-version: "1.21.4"
author: StoryTimeProductions
description: A collection of in-house tweaks for the StoryTime SMP. Currently includes the Stracker module for daily playtime tracking.

commands:
  ststatus:
    description: Shows how much time you've actively played today
    usage: "/ststatus"
    aliases: status
  stboost:
    description: Boosts multiplier for community participation (WIP)
    usage: "/stboost"
    aliases: boost
  stlobby:
    description: Teleport to the lobby
    usage: /stlobby
    aliases: lobby

permissions:
  stweaks.status:
    description: Allows access to /ststatus
    default: true
  stweaks.boost:
    description: Allows use of /stboost
    default: op
  stweaks.lobby:
    description: Allows access to /stlobby
    default: true
  stweaks.*:
    description: Grants all Stweaks permissions
    default: false
    children:
      stweaks.status: true
      stweaks.boost: true
      stweaks.lobby: true
